[package]
name = "gol3d"
version = "0.1.0"
authors = ["Nicolas Senaud <nicolas@senaud.fr>"]

[dependencies]
log = "0.3.7"
env_logger = "0.4.2"
glium = "*"
nalgebra = "0.11.1"
ndarray = "0.8.0"
kiss3d = "0.8.0"
